- src/main/java/org/codehaus/mojo/versions/SetMojo.java
When using an alternate pom with `mvn -f alternate-pom.xml versions:set -DnewVersion=0.0.1`, submodule versions are updated, but not the parent pom version.
This fix works with an alternate pom and with a classic `pom.xml`
> fix versions:set when used with an alternate POM

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
Adds support to allow locking of parent snapshot versions
resolves issue #47
> processParent option added to versions:lock-snapshots

- src/it-repo/dummy-api-1.1-SNAPSHOT.pom
- src/it/it-use-releases-003/invoker.properties
- src/it/it-use-releases-003/pom.xml
- src/it/it-use-releases-003/verify.bsh
- src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
Second try, now with test (Replaces #86)
Original text:
In order to use this plugin we had to enhance the behaviour of the `UseReleasesMojo`.
Before, if the version that should be replaced was `1.0-SNAPSHOT`, it would only look for a matching release with the version `1.0`.
Due to our continous-integration pipeline we needed the functionality that `1.0-SNAPSHOT` should be replaced with the highest matching version `1.0.x.y` (e.g. `1.0.1.100`).
This pull request implements this behaviour, it can be activated with the property `allowRangeMatching`. Also, if no matching snapshot is found, the property `failIfNotReplaced` causes the build to immediately fail.
Both properties default to `false` so that the default behaviour is not changed.
We considered using `force-releases`, but that had the …
> UseReleases: now with allowRangeMatching and failIfNotReplaced + test

- src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
When updating versions, this will always provide the latest release version unless -DallowSnapshots=true
As an example, if I have a dependency A and it has version:
1.5.1-SNAPSHOT but the latest release in my repo is 1.5.0,
then the update will replace this version with 1.5.0.
If -DallowSnapshots=true is specified, then the version will be replaced with the latest snapshot.
> Always provide latest release version.

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
Added new goal (“use-dep-version”), to allow specification of a
specific version for a specific dependency. This is something we have
been using internally to manage versions for a very large (100+ module)
project where we can’t always use the most up-to-date version of a
particular third party component.
> new goal: use-dep-version

- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
For example, a mapped drive in Windows
> versions:set: fix NullPointerException if project is in root directory

- src/site/apt/examples/use-releases.apt
"unlock-snapshots" goal used in documentation for goal "use-releases", but should be use-releases.
The dependency listed prior to mentioning the command contains a snapshot version. The dependency listed after mentioning the command contains the corresponding final version. The operation applied here is not related to "unlock-snapshots", but to "use-releases".
> Fix wrong goal mentioned in docu

- src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
This fixes resolution of snapshot dependencies with classifiers.
If you depended on ex. a class tests of packaging jar from a artifact with no jar without packaging the previous snapshot resolution would fail.
> Fix locking of snapshots with classifier

- src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
- src/test/resources/org/codehaus/mojo/versions/api/PomHelperTest.dependencyManagementBOMs.pom.xml
+ added PomHelper.readImportedPOMsFromDependencyManagementSection in order to read imported POMs from raw pom.xml
* UseReleases process imported POMs when processing dependencyManagement
* fixed spelling mistake in javadoc for PomHelperTest
> Fix for #134: Goal: use-releases doesn't processes imported POMs in dependencyManagement

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
The documentation listed here makes it seem like this flag should process the parent section of the POM (and remove -SNAPSHOT), but that functionality wasn't there.
> Fixed #153: 'processParent' not working for use-releases goal

- ReleaseNotes.md
- pom.xml
- src/it/it-set-scm-tag-001/invoker.properties
- src/it/it-set-scm-tag-001/pom.xml
- src/it/it-set-scm-tag-001/verify.bsh
- src/it/it-set-scm-tag-002/invoker.properties
- src/it/it-set-scm-tag-002/pom.xml
- src/it/it-set-scm-tag-003/invoker.properties
- src/it/it-set-scm-tag-003/pom.xml
- src/it/it-set-scm-tag-004/invoker.properties
- src/it/it-set-scm-tag-004/module-a1/pom.xml
- src/it/it-set-scm-tag-004/module-a2/pom.xml
- src/it/it-set-scm-tag-004/pom.xml
- src/it/it-set-scm-tag-004/verify.bsh
- src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
Closes #182
Usage:
`mvn versions:set-scm-tag -DnewTag=v1.0.0 -DgenerateBackupPoms=false`
> Add Mojo for setting the SCM tag

- pom.xml
Hereafter will be better aggregated in Maven licence reports
> Align license name to ASF standard from parent-pom

- pom.xml
- src/it-repo/test/bigversion/dummy-lib-1.1.1.1.jar
- src/it-repo/test/bigversion/dummy-lib-1.1.1.1.pom
- src/it-repo/test/bigversion/dummy-lib-2.0.0.0.jar
- src/it-repo/test/bigversion/dummy-lib-2.0.0.0.pom
- src/it-repo/test/bigversion/dummy-lib-2.0.10.0.jar
- src/it-repo/test/bigversion/dummy-lib-2.0.10.0.pom
- src/it-repo/test/bigversion/dummy-lib-2.12.0.0.jar
- src/it-repo/test/bigversion/dummy-lib-2.12.0.0.pom
- src/it-repo/test/bigversion/dummy-lib-3.0.0.0-SNAPSHOT.jar
- src/it-repo/test/bigversion/dummy-lib-3.0.0.0-SNAPSHOT.pom
- src/it/it-use-latest-versions-012/invoker.properties
- src/it/it-use-latest-versions-012/pom.xml
- src/it/it-use-latest-versions-012/verify.bsh
- src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java
- src/test/java/org/codehaus/mojo/versions/api/ArtifactVersionsTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilterTest.java
Fixes the incorrect logic in the `MajorMinorIncrementalFilter` that caused numerous issues.
Fixes #304 for which tests are included and this was targetted.
I also beleive (and there is some minimal test for it) #296 #295 #282 
ITs pass on maven `3.5.2`  as the ordering and parsing relies on some fixes in Maven 3.x they may or may not pass on maven 2.x.
@stephenc @khmarbaise @olamy
> Non default versions

- src/main/mdo/rule.mdo
- src/site/apt/version-rules.apt.vm
As discussed in #157, custom rulesets will remain in 3.0.0.
This PR removes the no-longer-accurate deprecation warnings.
Closes #157.
> Remove notice of deprecation for comparison rules

- pom.xml
Fixes these problems in the JDK16 build:
```
[INFO] run post-build script verify.bsh
[INFO]   The post-build script did not succeed. Sourced file: inline evaluation of: ``import java.io.*; import java.util.regex.*;  try {     File file = new File( bas . . . '' unknown error: Unable to make public java.lang.AbstractStringBuilder java.lang.AbstractStringBuilder.append(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @430c04a6
[INFO]           it-update-child-modules-002/pom.xml .............. FAILED (6.3 s)
```
This should be merged ASAP since all more or less recent PRs are affected by this problem (and `master` of course). /cc @sparsick @mfriedenhagen
I guess sooner or later dependabot would have created a PR for this update, but given the …
> Update maven-invoker-plugin to 3.2.2 to fix JDK16 build

- src/it/it-resolve-ranges-issue-442/invoker.properties
- src/it/it-resolve-ranges-issue-442/pom.xml
- src/it/it-resolve-ranges-issue-442/verify.groovy
- src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
* `mvn validate` does choke on dependencies without versions.
* However in managed dependencies a missing version is ignored.
* resolve-ranges does throw a NPE, which is not helpful.
* So fail with available coordinates to make fixing easier.
* When the artifactId is missing in a managed dependency Maven core
will aready fail.
Resolve #442
> fix(resolve-ranges): fail properly on managed dep without version

- src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReport.java
"Plugin Updates Report" and "Dependency Updates Report" are both already sorted by alphabetical order. while "Property Updates Report" was sorted by hash keys. Sorting this report by Property name will make it consistent with others and more readable.
> Sort properties by Property name in "Property Updates Report"

- src/main/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRenderer.java
- src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
- src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/PluginUpdatesXmlRenderer.java
- src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
- src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorsTest.java
Fixes #466 
o Removed not needed calls to toString() to improve the code base
> Removal of not needed calls to toString() in the code base

- pom.xml
Updated the dependencies to use JUnit 5 instead of JUnit 4. The usage of the JUnit Vintage plattform ensures, that the existing test can be executed without any changes.
Fixed #472
> Use JUnit 5 instead of JUnit 4

- README.md
- src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
- src/main/java/org/codehaus/mojo/versions/utils/PropertiesVersionsFileReader.java
- src/site/apt/index.apt
- src/test/java/org/codehaus/mojo/versions/utils/PropertiesVersionsFileReaderTest.java
- src/test/resources/org/codehaus/mojo/versions/utils/testPropertiesVersionsFile.properties
Fixes #469
Possibility to use set-property with `-DpropertiesVersionsFile` to set multiple properties.
Useful to update values of multiples properties in pom with 1 call.
Example:
```properties
#test.properties
compo1.version=1.2.3
compo2.version=4.5.6
```
To update all properties in pom.xml in one call:
```
mvn version:set-property -DpropertiesVersionsFile=test.properties
```
> Fixes #469 Support.property file in set-property

- src/it/it-dependency-updates-report-001/verify.bsh
- src/it/it-dependency-updates-report-003/verify.bsh
- src/it/it-dependency-updates-report-004/verify.bsh
- src/it/it-plugin-updates-report-001/verify.bsh
- src/it/it-plugin-updates-report-002/verify.bsh
- src/it/it-plugin-updates-report-003/verify.bsh
- src/it/it-property-updates-report-001/verify.bsh
- src/main/java/org/codehaus/mojo/versions/AbstractVersionsReportRenderer.java
- src/main/java/org/codehaus/mojo/versions/PluginUpdatesRenderer.java
- src/main/resources/dependency-updates-report.properties
- src/main/resources/plugin-updates-report.properties
- src/main/resources/property-updates-report.properties
> [Enhancement] Display "Latest" Versions in Reports Summary

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
* enable version resolver for semantic plugin versioning based on tags
* make sure name-template and tag-template are always in sync
* provide a default release text template
* it's also useful to be able to start the workflow manually when tags are added/updated after the last run
> Configure Release Drafter for Semantic Versioning

- .gitignore
- src/it/it-set-019-outputTimestamp/invoker.properties
- src/it/it-set-019-outputTimestamp/pom.xml
- src/it/it-set-019-outputTimestamp/verify.groovy
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
> #453 update Reproducible Builds outputTimestamp when setting version

- src/it/it-set-018-issue-82/invoker.properties
- src/it/it-set-019-issue-426/invoker.properties
- src/it/it-set-019-issue-426/module-a1/module-b1/pom.xml
- src/it/it-set-019-issue-426/module-a1/module-b2/pom.xml
- src/it/it-set-019-issue-426/module-a1/module-b3/pom.xml
- src/it/it-set-019-issue-426/module-a1/pom.xml
- src/it/it-set-019-issue-426/module-a2/pom.xml
- src/it/it-set-019-issue-426/pom.xml
- src/it/it-set-019-issue-426/verify.groovy
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
introduce a new flag processFromLocalAggregationRoot that enables the new (and probably more correct) behavior by setting it it false
ensure old and new behavior are covered by integration tests
Fixes #426
> Fixes #426 restore default behavior on setting versions in all modules of the local aggregation root that was present before the fix for #82

- src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
- ensure either 'properties' or 'propertiesVersionFile' is provided
- fix validation of superfluous newVersion parameter
fixes #544
> #544 set-property: improve validation of plugin parameters:

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsReportRenderer.java
https://github.com/mojohaus/versions-maven-plugin/issues/536
Maven Site Plugin and Doxia switching to HTML 5 broke all the reports that includes images.
Including other report plugins.
The proposed fix allows to return back to the original compact format that was more synthetic.
> Fixed regression in the maven site rendering

- src/it/it-set-020-outputTimestamp-disabled/invoker.properties
- src/it/it-set-020-outputTimestamp-disabled/pom.xml
- src/it/it-set-020-outputTimestamp-disabled/verify.groovy
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
> #568 introduce updateBuildOutputTimestamp property to make it configurable whether project.build.outputTimestamp is updated or not

- src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
- src/site/apt/index.apt
* add a description
* include in in the goal list in index.apt
* also remove deprecated/unused `requiresDirectInvocation` parameter
> use-dep-version mojo: add a description

- src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
bugfix for parentVersion wrongly be String "null" when be missing and should be null be default
> bugfix for parentVersion wrongly be String "null" when be missing and should be null be default

- src/it-repo/dummy-parent-issue-582-1.0.pom
- src/it/it-update-properties-issue-582/invoker.properties
- src/it/it-update-properties-issue-582/pom.xml
- src/it/it-update-properties-issue-582/verify.groovy
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
Fixed #582
o Updated PomHelper to validate version properties also across parents.
> Fix for issue #582 - update-properties does not work across parent-child pom 

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
https://github.com/mojohaus/versions-maven-plugin/issues/627
Quick fix + a unit test
> Reordering the checks in shouldApplyUpdate + a simple unit test

- src/it/it-set-021-outputTimestampPolicy-always/invoker.properties
- src/it/it-set-021-outputTimestampPolicy-always/pom.xml
- src/it/it-set-021-outputTimestampPolicy-always/verify.groovy
- src/it/it-set-022-outputTimestampPolicy-onchange/invoker.properties
- src/it/it-set-022-outputTimestampPolicy-onchange/pom.xml
- src/it/it-set-022-outputTimestampPolicy-onchange/verify.groovy
- src/it/it-set-023-outputTimestampPolicy-never/invoker.properties
- src/it/it-set-023-outputTimestampPolicy-never/pom.xml
- src/it/it-set-023-outputTimestampPolicy-never/verify.groovy
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
o New property: updateBuildOutputTimestampPolicy = (onchange | always | never)
> New property: updateBuildOutputTimestampPolicy = (onchange | always | never) (#595)

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
- src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
- src/main/java/org/codehaus/mojo/versions/PluginUpdatesReport.java
- src/main/java/org/codehaus/mojo/versions/utils/MiscUtils.java
- src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
- src/test/java/org/codehaus/mojo/versions/PluginUpdatesReportTest.java
Added `onlyUpgradable`, which will restrict the reports to only show upgradable artifacts, and `onlyProjectDependencies`, `onlyProjectPlugins`, which will restrict the graph of demendencyManagement/pluginManagement artifacts to the graph used in the project.
Additionally, some refactoring and improvements.
Most importantly in class `AbstractVersionsReport`, which redefined some of its superclass attributes in order to restrict access (?), which was apparently never used and could only create confusion. Simplified.
> Limit to only artifacts that have updates and are in the dependency graph (#589)

- src/it/it-property-updates-report-001/pom.xml
- src/it/it-property-updates-report-002-slow/invoker.properties
- src/it/it-property-updates-report-002-slow/maven-version-rules.xml
- src/it/it-property-updates-report-002-slow/pom.xml
- src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
This was identified as a performance hotspot and the result is static
for each run, adding a cache dramatically speeds up some executions.
The included IT shows the problem: Without this optimization, it runs
over a minute, with the fix it finishes instantly.
(Reopened from #365 because I did stupid things with our fork)
> Cache result of getBestFitRule (fixes #575)

- src/it/it-abstract-versions-report-001/invoker.properties
- src/it/it-abstract-versions-report-001/pom.xml
- src/it/it-abstract-versions-report-001/verify.groovy
- src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
AbstractMavenReport from maven-reporting-impl:3.2.0 introduced the `localRepository` property, which was supposed to be initialized from a parameter with the same name, and if the same was not supplied, from `${localRepository}`. Unfortunately, it was shadowed by `AbstractVersionsReport`
> Fix for issue #648: de-shadowing the localRepository property

- src/main/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRenderer.java
- src/test/java/org/codehaus/mojo/versions/DependencyUpdatesXmlRendererTest.java
DependencyUpdatesXmlRenderer::getVersionsBlocks is used for both dependency and plugins xml report blocks. While the html renderer uses the version as specified in the Dependency class (which is a range if there's no current version specified), the XML renderer only uses an ArtifactVersions object. 
In this PR I'm mimicking the behaviour of the HTML renderer in that regard, i.e. using the range if a concrete version is not given.
> Fix for issue #323: using version range if currentVersion is not available for DependencyUpdatesXmlRenderer

- src/it/it-set-024-versionless-dependency/child/pom.xml
- src/it/it-set-024-versionless-dependency/invoker.properties
- src/it/it-set-024-versionless-dependency/pom.xml
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
Fixing an NPE in DependecyVersionChanger if the old version is null + checkstyle fixes + some minor refactoring.
Edit: There's no verification in that test case as the test is considered successful if no exception is raised :-)
> Fixing #604: npe in DependencyVersionChanger if artifact version is null

- src/test/java/org/codehaus/mojo/versions/utils/BaseMojoTestCase.java
Simple extension of `AbstractMojoTestCase`, adding the possibility of injecting a project without having to create project stubs.
Example usage:
```java
@Test
public void testVersionlessDependency() throws Exception
{
SetMojo myMojo = createMojo( "set", "src/test/resources/org/codehaus/mojo/set/versionless-01/pom.xml" );
assertNotNull( myMojo );
myMojo.execute();
}
```
> Extension of AbstractMojoTestCase from maven testing harness: injecting projects w/o creating stubs

- pom.xml
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- src/main/java/org/codehaus/mojo/versions/utils/RegexUtils.java
- src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
- src/test/resources/org/codehaus/mojo/set/versionless-01/pom.xml
Fixing an NPE when a trying to upgrade a dependency with a version specified in dependencyManagement.
Added some minor refactoring where I modified the files anyway + fixed some obvious vulnerabilities (comparison against a possible null value etc)
> Fixing #654: NPE in SetMojo when a dependency version is null

- src/test/java/org/codehaus/mojo/versions/utils/BaseMojoTestCase.java
A small correction to #656: it was previously restricted to SetMojo only, now making it more generic. A problem is that we're trying to access a property by name, perhaps there should be a common interface instead, but that's for another PR.
> Fix: making createMojo return Mojo objects (was previously restricted to SetMojo)

- pom.xml
- src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
- src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
New argument: `allowDowngrade`, which will downgrade a snapshot version if these are not allowed. Only valid if `allowSnapshots` is `false`.
> Implementing #213: new argument: allowDowngrade, which will downgrade a snapshot if these are disallowed

- src/main/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReader.java
- src/test/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReaderTest.java
Small fix on delta computation in +replace and +replaceMark methods. Plus a simple unit test.
> Fixing #320: Correcting delta computation in ModifiedPomXMLEventReader

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/ArtifactVersions.java
- src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
- src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
- src/test/java/org/codehaus/mojo/versions/utils/TestChangeRecorder.java
UpdateParentMojo: added "allowDowngrade", default "false", fixed range handling wrt downgrading. Added a unit test.
This is the same as #662 rebased and squashed (rebasing the original one didn't work for some reason).
>  Fixing #231 bug/feature: added "allowDowngrade", default "false", fixed range handling wrt downgrading

- src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
- src/test/java/org/codehaus/mojo/versions/SetPropertyMojoTest.java
- src/test/java/org/codehaus/mojo/versions/utils/BaseMojoTestCase.java
- src/test/resources/org/codehaus/mojo/set-property/null-new-version-pom.xml
- src/test/resources/org/codehaus/mojo/set-property/null-property-pom.xml
> Fixing #315: Guarding against newVersion or property being empty if the properties file is not provided

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
- src/main/java/org/codehaus/mojo/versions/PluginUpdatesDetails.java
- src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
- src/main/java/org/codehaus/mojo/versions/api/UpdateScope.java
- src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
- src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/InvalidSegmentException.java
- src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/NumericVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/VersionComparator.java
- src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorsTest.java
The situations indicated in the exceptions were not handled properly throughout the code, in some places, `MojoExcecutionException` was simply being thrown leading to the whole run being stopped; `InvalidVersionSpecificationException` was unchecked, leading to the same.
Handling those situations in the Mojo itself rather than in the methods so that a proper handling could be effected where necessary.
Because of all that, a rather sizeable refactoring was due.
More PRs will follow, I want to refactor and polish the code more, but this one is what's necessary for resolving this issue.
So, like I said in the linked issue:
The more I look into it, the more issues I see:
- segment appears to be 0-based (see e.g. `AbstractVersionsUpaterMojo.determineUnchangedSegment` or …
> Fixing #251: proper handling of InvalidSegmentException and InvalidVersionSpecificationException

- src/it/it-display-dependency-updates-issue-258-dependencyIncludesAndExcludes/invoker.properties
- src/it/it-display-dependency-updates-issue-258-dependencyIncludesAndExcludes/pom.xml
- src/it/it-display-dependency-updates-issue-258-dependencyIncludesAndExcludes/verify.groovy
- src/it/it-display-dependency-updates-issue-318-dependencyExcludes/verify.groovy
- src/it/it-display-dependency-updates-issue-318-dependencyIncludes-multi/verify.groovy
- src/it/it-display-dependency-updates-issue-318-dependencyIncludes/verify.groovy
- src/it/it-display-dependency-updates-issue-318-dependencyIncludesAndExcludes/verify.groovy
- src/it/it-display-dependency-updates-issue-318-dependencyManagementExcludes/verify.groovy
- src/it/it-display-dependency-updates-issue-318-dependencyManagementIncludes/verify.groovy
- src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
This simple and short PR extends the closed scope of #258 by adding filtering to plugin and plugin management.
@slawekjaranowski please review.
> Amended #258: Adding plugin and plugin management dependency includes/excludes

- src/it-repo/dummy-parent4-70.pom
- src/it-repo/dummy-parent4-71-SNAPSHOT.pom
- src/it/it-update-parent-005-issue-670/invoker.properties
- src/it/it-update-parent-005-issue-670/pom.xml
- src/it/it-update-parent-005-issue-670/verify.groovy
- src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
- src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
Fixing the problem related to snapshots in UpdateParentMojo + adding a unit test testing snapshots.
> Fixing #670: restoring allowSnapshots which was disabled in PR #665

- pom.xml
- src/test/java/org/codehaus/mojo/versions/UseDepVersionMojoTest.java
- src/test/java/org/codehaus/mojo/versions/utils/BaseMojoTestCase.java
- src/test/resources/org/codehaus/mojo/use-dep-version/issue-637-pom.xml
Reason for the NPE: the new version of maven-common-artifact-filters, class `PatternIncludesArtifactFilters` (line 593) expects the "artifactoid" to return a non-null value for every field when the pattern contains a wildcard character.
The "artifactoid" is a functional interface basically returning the desired segment (coordinate in the code) of the artifact. The classifer is not set, hence equal null; this leads to NPE.
> #673: Fixing NPE in UseDepVersionMojo caused by PatternIncludesArtifactFilter expecting a non-null classifier when using wildcards

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsReport.java
- src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
- src/main/java/org/codehaus/mojo/versions/api/UpdateScope.java
- src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
i have a PR waiting to be pushed/suggested but i need these methods to be refactored first so i dont fall into more than 7 parameters compiler errors + the new design i suggest makes the methods more easy to maintain.
i know this does not add any more features but i hope this can be usefull for the quality and ease of maintenance there after.
the basics are sending a Restriction parameter instead of 4 (lower/upper bound and accept booleans), thus gaining 3 more free params to send for other features (next PR to filter RCs is waiting for this one to be accepted)
Thank you for your time
> Restriction parameter to prevent more than 7 parameters in the next PRs

- src/it/it-update-parent-005-issue-610/invoker.properties
- src/it/it-update-parent-005-issue-610/pom.xml
- src/it/it-update-parent-005-issue-610/verify.groovy
- src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
- src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
As explained in #610 
If `parentVersion` is set, `skipResolution` will cause the mojo to completely skip version resolution and will simply set the parent version to the given version. 
Added tests + enhanced the documentation.
> Issue 610 update-parent: add a possibility to skip version resolution and enforce a parent version

- src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- src/test/java/org/codehaus/mojo/versions/SetScmTagMojoTest.java
- src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
- src/test/java/org/codehaus/mojo/versions/utils/ModifiedPomXMLEventReaderUtils.java
- src/test/resources/org/codehaus/mojo/set-scm-tag/issue-342-pom.xml
- src/test/resources/org/codehaus/mojo/set-scm-tag/pom.xml
This is some enhancement of the scm-tag functionality. Whereas it was only possible to add new values to the existing scm subelements, this enhancement adds the possibility to add missing elements as well.
In the code, I've replaced stack usage with reflection in PomHelper, but it doesn't really make a difference (can revert it if necessary, I think it's a question of taste). Plus, encapsulated some implementation details, recursion state (drawback of using recursion), and helper methods within a local class.
It's not fully flexible -- it doesn't allow us to create new elements if also the parent element is missing -- but since it's not XSD-aware, it wouldn't know where to put the new element :)
> Issue 342 scm set tag add new elements

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
- src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseNextSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
- src/main/java/org/codehaus/mojo/versions/api/Segment.java
- src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/InvalidSegmentException.java
- src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java
- src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/NumericVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/VersionComparator.java
- src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorsTest.java
Further refactoring of the int-based segments, replacing the integer-based segments with the enum.
> Further refactoring: replacing segment index with the Segment enum

- src/it/it-dependency-updates-report-001/verify.bsh
- src/it/it-plugin-updates-report-001/verify.bsh
- src/main/java/org/codehaus/mojo/versions/AbstractVersionsReportRenderer.java
- src/main/java/org/codehaus/mojo/versions/PluginUpdatesRenderer.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
- src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
- src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
- src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
#632 Fix Bounds so lower and upper bounds keep milestones and rcs in the same majors when they are.
a quick before/after :
> #632 Fixed lower and upper bounds to keep milestones and rcs in the right majors.

- src/main/java/org/codehaus/mojo/versions/SetMojo.java
- src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
- src/test/resources/org/codehaus/mojo/set/remove-snapshot/pom.xml
See #709 
Making the removeSnapshot option idempotent
> Implementing #709: removeSnapshot idempotency

- src/it/it-parent-updates-report-001/invoker.properties
- src/it/it-parent-updates-report-001/module/pom.xml
- src/it/it-parent-updates-report-001/pom.xml
- src/it/it-parent-updates-report-001/src/site/site.xml
- src/it/it-parent-updates-report-001/verify.groovy
- src/main/java/org/codehaus/mojo/versions/DependencyUpdatesRenderer.java
- src/main/java/org/codehaus/mojo/versions/ParentUpdatesReport.java
- src/main/resources/parent-updates-report.properties
- src/site/apt/index.apt
- src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
- src/test/java/org/codehaus/mojo/versions/ParentUpdatesReportTest.java
- src/test/java/org/codehaus/mojo/versions/utils/MockUtils.java
Implementing the requested enhancement + added an it and a unit test.
I plan on adding aggregate reports in another PR as a response to a request in another issue -- I think it's a perfectly valid request.
Also, I want to refactor the whole reports suite (and maybe try using velocity?), all of them, but that's for another PR.
> #343 Parent updates report

- src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
Second batch of maintenance following PR #672.
"as a result of fixing #632, it appears we could maybe get rid of the class MajorMinorIncrementalFilter which states that its very existence is filtering milestones and RC from the result of the calls, when they are in the wrong major, but they are now already filtered out by the corrected boundaries."
> #632 Second batch of maintenance following PR #672

- src/it/it-revert-isssue-265/aggregate/pom.xml
- src/it/it-revert-isssue-265/invoker.properties
- src/it/it-revert-isssue-265/module-a/pom.xml
- src/it/it-revert-isssue-265/module-b/pom.xml
- src/it/it-revert-isssue-265/verify.groovy
- src/main/java/org/codehaus/mojo/versions/RevertMojo.java
- src/test/java/org/codehaus/mojo/versions/RevertMojoTest.java
- src/test/resources/org/codehaus/mojo/revert/issue-265/aggregate/pom.xml
- src/test/resources/org/codehaus/mojo/revert/issue-265/aggregate/pom.xml.versionsBackup
- src/test/resources/org/codehaus/mojo/revert/issue-265/module-a/pom.xml
- src/test/resources/org/codehaus/mojo/revert/issue-265/module-a/pom.xml.versionsBackup
- src/test/resources/org/codehaus/mojo/revert/issue-265/module-b/pom.xml
- src/test/resources/org/codehaus/mojo/revert/issue-265/module-b/pom.xml.versionsBackup
Using `PomHelper::getAllChildModules` to retrieve all modules in the reactor to get files to revert. Relying on maven to process all enabled profiles did not revert all files changed by `SetMojo`, because `SetMojo` also uses `getAllChildModules`.
> Issue #265: revert mojo to scan child modules instead of relying on maven

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/AbstractVersionsReportRenderer.java
- src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
- src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- src/main/java/org/codehaus/mojo/versions/api/Segment.java
- src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
- src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersion.java
- src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
- src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
- src/main/java/org/codehaus/mojo/versions/ordering/VersionComparator.java
- src/site/apt/examples/advancing-dependency-versions.apt.vm
- src/site/apt/examples/display-plugin-updates.apt
- src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
- src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
- src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
- src/test/java/org/codehaus/mojo/versions/api/ArtifactVersionsTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/utils/MockUtils.java
Instead of using the next version for range calculation when considering version upgrades, I've devised a sort of a bounded artifact version where we use the concept of "infinity" on a given segment position to match all possible upper versions on the position, but nothing from the more major segment. So, 2.0.0-beta or similar won't be matched anymore when considering minor updates of the 1.x.x branch.
Tests added as unit tests; in particular, two for testing the case explained in #454 in `DisplayDependencyUpdatesMojoTest`
Some minor refactoring and typo corrections.
> #454: Introducing "infinity-like" range calculus for dependency range computation

- pom.xml
This test should be used for profiling and not as part of integration testing. Caching rule resolution is a good start, but the actual performance depends on the machine and conditions of the cluster, but tests should not really depend on the volatile cluster state.
> #729: Ignoring the flipper

- src/site/markdown/version-rules.md.vm
I thought it would be nice to link to the actual Maven version specification instead of the DefaultArtifactVersion as the description of the versioning rules.
> Add a link to the actual Maven versioning specification

- src/main/java/org/codehaus/mojo/versions/api/ArtifactVersionsCache.java
- src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
- src/main/java/org/codehaus/mojo/versions/reporting/DependencyUpdatesReportRenderer.java
- src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
- src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
Noticed some duplication of calls to `AbstractVersionDetails::getOldestUpdate` and similar: e.g. the same information is retrieved first during the rendering of the "Overview" section to gather aggregate information, then the call is repeated to render update details.
> Caching update information in reports to increase performance

- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
While working on the caching PR for the reports, I couldn't fail to notice that we're using the AbstractVersionDetails as the interface in many cases whilst the methods could be moved to the API instead.
Reordered some methods in the interface to adhere closer to the AbstractVersionDetails class.
Once this is merged, the AbstractVersionDetails calls could be replaced by VersionDetails.
> Adding some of the remaining AbstractVersionDetails methods to the interface

- src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
- src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/MavenVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparatorTest.java
- src/test/java/org/codehaus/mojo/versions/ordering/NumericVersionComparatorTest.java
Fixing the wrong reported number of updates with qualified versions (versions with a qualifier).
> #760: Fixing the reported number of updates

- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- src/test/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojoTest.java
- src/test/java/org/codehaus/mojo/versions/utils/TestUtils.java
- src/test/resources/org/codehaus/mojo/display-property-updates/issue-367/child/pom.xml
- src/test/resources/org/codehaus/mojo/display-property-updates/issue-367/pom.xml
Includes parent projects in property resolution for property updates. Instead of only considering the model of the current project, will also consult parent models to see if there are property definitions for properties defined in the current project.
> #367: Include parent projects in property resolution

- src/main/java/org/codehaus/mojo/versions/utils/SegmentUtils.java
When execute: `mvn versions:display-property-updates` I see output like:
```
[INFO] --- versions-maven-plugin:2.12.0:display-property-updates (default-cli) @ parent ---
[INFO] Major version changes allowed
[INFO] Major version changes allowed
[INFO] Major version changes allowed
....
[INFO] Major version changes allowed
[INFO] Major version changes allowed
[INFO] Major version changes allowed
[INFO] 
[INFO] The following version properties are referencing the newest available version:
[INFO]   ${build-helper-maven-plugin.version} .......................... 3.3.0
[INFO]   ${jacoco-maven-plugin.version} ................................ 0.8.8
....
```
The log `Major version changes allowed` is printed many times for each property without context.
I think it not give any useful information in …
> Remove redundant logs in info level

- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
Uses Streams API to streamline some of the methods, more concise and more readable in my (subjective) opinion.
Does not need to be added to the upcoming release.
> Minor enhancement: use streams API in getNewestUpdates and getVersions

- src/main/java/org/codehaus/mojo/versions/utils/SegmentUtils.java
- src/test/java/org/codehaus/mojo/versions/utils/SegmentUtilsTest.java
Obvious fix + unit tests.
Please add to the release if still possible.
> Fixing #769

- src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
- src/main/java/org/codehaus/mojo/versions/PluginUpdatesReportMojo.java
- src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
- src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
- src/test/java/org/codehaus/mojo/versions/PluginUpdatesReportMojoTest.java
Root cause of the issue: `VersionsHelper.lookupDependenciesUpdates` actually returns all dependency versions, and not just updates.
The problem manifested itself when the currently used version was the latest, but there were more versions reported (older than the current one).
This is now corrected, i.e. the method returns only updates, in contrast to `lookupArtifactVersions`.
`onlyUpgradableOnly` looks to work fine now. Updated the unit tests to test also for cases when the version used by an artifact is the latest version, but there are more available versions (older than the current one).
Removed some redundant classes implementing `Callable`, which could very easily be inlined which results in a much cleaner code.
Also, as a minor pedantic fix, corrected the "splitted" [sic] to …
> Resolves #776: onlyUpgradable change the filter to versions where the current version is not the latest one

- src/site/markdown/examples/setaggregator.md
@slachiewicz please review and merge
> #725: Migrate Set Aggregator to Markdown

- src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
Unfortunately, there is already a bug report. Fixed and added some more unit tests (which we clearly badly need).
> Resolves #790: Fix update scope determination in DisplayDependencyUpdatesMojo

- src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
- src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
- src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojo.java
- src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
- src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
- src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
- src/test/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojoTest.java
- src/test/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojoTest.java
- src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
Introducing a new parameter: `includeParent`, default `true` so that it would be possible to disable consulting parent POMs when resolving properties. This might come especially handy in projects using large parents like e.g. one of Spring Boot.
> Resolves #793: Added includeParent to DisplayPropertyUpdates and PropertyUpdatesReport

- src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
- src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
- src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
- src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
- src/test/resources/org/codehaus/mojo/display-dependency-updates/version-interpolation/pom.xml
> #614 resolve version from model properties if necessary

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-794/pom.xml
Probably an old technical debt of sorts in SetMojo: the mojo would normally change the files matching oldVersion, groupId, or ArtifactId.
However, if no match was found in the reactor, then the root model is changed anyway!
https://github.com/mojohaus/versions-maven-plugin/blob/b75a5656113f8974e7bb26f2cd0cdeacff59800e/src/main/java/org/codehaus/mojo/versions/SetMojo.java#L384
I don't understand the reason for it. When checked git blame, the original author added those lines to fix some breaking integration tests. However, it looks like no tests fail even with those lines removed.
Anyhow. I don't think that behaviour was intuitive and it is certainly very unexpected.
A side effect of that behaviour was that, with "always", the timestamp of the file was updated regardless if a match was …
> #794: SetMojo would always change the version of the POM, regardless if a match was found

- versions-maven-plugin/src/it/it-set-issue-505/invoker.properties
- versions-maven-plugin/src/it/it-set-issue-505/moduleA/moduleB/pom.xml
- versions-maven-plugin/src/it/it-set-issue-505/moduleA/pom.xml
- versions-maven-plugin/src/it/it-set-issue-505/pom.xml
- versions-maven-plugin/src/it/it-set-issue-505/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/versions/api/issue-505/moduleA/moduleA.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/versions/api/issue-505/moduleA/moduleB/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/versions/api/issue-505/pom.xml
Nothing fancy or spectacular, just a simple bug fix for the edge case of having the module name include the pom.xml file path. In the unpatched implementation, the "/pom.xml" was treated as part of the directory name when descending down the module tree to retrieve child models... Fixed that.
Added some tests (unit test for the PomHelper method + integration test for the use case from the issue).
> Resolves #505: getReactorModels using correct module paths when the module name includes pom.xml

- model-report/pom.xml
- model-report/src/main/mdo/plugin-updates-report.mdo
- model-report/src/main/mdo/property-updates-report.mdo
- versions-maven-plugin/src/it/it-xml-property-updates-report-001/invoker.properties
- versions-maven-plugin/src/it/it-xml-property-updates-report-001/pom.xml
- versions-maven-plugin/src/it/it-xml-property-updates-report-001/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/OverviewStats.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginOverviewStats.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/CommonXmlReportRendererUtils.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/PluginUpdatesXmlReportRenderer.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/xml/PropertyUpdatesXmlReportRenderer.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojoTest.java
XML version of the Property Updates Report
> Resolves #359: XML Property Updates Report

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
- versions-maven-plugin/src/site/markdown/index.md
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
- Abstracting a common base for UseLatestVersionsMojo and UseLatestReleasesMojo.
- Elaborating on the difference between a "release" and a "version"
Two issues:
#807 
#516
> Resolves #807: Abstracting a common base for UseLatestVersionsMojo and UseLatestReleasesMojo

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/PropertyUpdatesReportMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojoTest.java
There have been compelling remarks that includeParent should be false, otherwise we're breaking backwards compatibility. I agree. Hence this small PR.
> Make includeParent false by default to retain backward compatibility.

- README.md
- pom.xml
- src/site/site.xml
- gitHub ribbon from parent project use artifact name, not valid for multi module
- stage site during build - one less a manual goal
> Site build - gitHub ribbon, stage site

- .github/workflows/maven.yml
We need the same goal for first build and for build in the matrix in order to skip the same build.
> GH build improvement - skip one build in matrix

- versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/DependencyUpdatesReportRenderer.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/VersionsReportRendererBase.java
- versions-maven-plugin/src/main/resources/dependency-updates-report.properties
the goal would be to shorten render methods by factorizing duplicate code
i'm not fully happy about the end result code so it's in draft but open to feedback/reviews
i believe the current code still gives a good idea of (some) cleaner methods
> Quality: Refactoring Reports classes

- versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- versions-maven-plugin/src/it/it-823-ranges-update-report-001/invoker.properties
- versions-maven-plugin/src/it/it-823-ranges-update-report-001/pom.xml
- versions-maven-plugin/src/it/it-823-ranges-update-report-001/verify.groovy
- versions-maven-plugin/src/it/it-823-ranges-update-report-002/invoker.properties
- versions-maven-plugin/src/it/it-823-ranges-update-report-002/pom.xml
- versions-maven-plugin/src/it/it-823-ranges-update-report-002/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/reporting/PropertyUpdatesReportRenderer.java
see issue:
* #767 (html reports covered, but not other types of reports)
* #824 (might need a second pr to fix other cases)
tasks:
> [#767] display update information for ranges

- .github/workflows/maven.yml
- README.md
According to clarification we can only test with the latest Maven on GitHub it will save time for executing
> Clarification in README - maintained versions, issues and PR creation

- versions-maven-plugin/src/it/it-update-properties-issue-837/invoker.properties
- versions-maven-plugin/src/it/it-update-properties-issue-837/parent-pom.xml
- versions-maven-plugin/src/it/it-update-properties-issue-837/pom.xml
- versions-maven-plugin/src/it/it-update-properties-issue-837/verify.groovy
- versions-maven-plugin/src/it/it-update-property-issue-837/invoker.properties
- versions-maven-plugin/src/it/it-update-property-issue-837/parent-pom.xml
- versions-maven-plugin/src/it/it-update-property-issue-837/pom.xml
- versions-maven-plugin/src/it/it-update-property-issue-837/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojoBase.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/update-properties/issue-837/parent-pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/update-properties/issue-837/pom.xml
Upon request of a user in #793, adding `includeParent` (`true` by default) to `UpdatePropertiesMojo`.
Setting it to `false` will speed up execution to a great extend without sacrificing accuracy in most cases. However, if the POM redefines properties used in parent POMs, dependencies bound to those properties will not be discovered, so the plugin will not redefine those properties. Therefore the default value is `true`.
> Resolves #837: Add includeParent (default true) to UpdatePropertiesMojo

- versions-maven-plugin/src/site/markdown/index.md
Adding aggregate plugins information to site
> #333: aggregated reports site information

- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
Quick fix, fixing a typo. No unit tests since it would require lots of mocking, and it was not possible to inject the RemoteRepositorySession object. And a WireMock test would be too much of an overkill for this IMO.
> Wagon should use remote repository instead of proxy repository for repo authentication

- versions-enforcer/src/site/markdown/index.md.vm
- versions-enforcer/src/site/site.xml
- versions-maven-plugin/src/site/markdown/index.md
We have only one enforcer rule so can be as main page of module
> Make Max Dependency enforcer rule as main page of enforcer module

- versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionDetails.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/ReactorDepthComparator.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
- versions-common/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
- versions-maven-plugin/src/it/it-set-issue-848/docs/moduleC/pom.xml
- versions-maven-plugin/src/it/it-set-issue-848/invoker.properties
- versions-maven-plugin/src/it/it-set-issue-848/moduleA/moduleA1.xml
- versions-maven-plugin/src/it/it-set-issue-848/moduleA/moduleA2.xml
- versions-maven-plugin/src/it/it-set-issue-848/moduleB/pom.xml
- versions-maven-plugin/src/it/it-set-issue-848/pom.xml
- versions-maven-plugin/src/it/it-set-issue-848/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateChildModulesMojo.java
@slawekjaranowski 
Please review.
> Resolves #848: Fixing module resolution with nonstandard filenames

- versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- versions-common/src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
Child modules were processed in a parallel stream which added elements to an unsynchonized LinkedHashMap.
This may resulted an incomplete set of child modules.
> #858 Fix child module resolution for multi-level projects

- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
- versions-enforcer/src/main/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdates.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
Relates to #855, reviewed and removed unsafe parallelStream usage where the terminator was not thread safe.
> Removes parallelStream use with non-thread safe collectors

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/parent-with-property/child/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/parent-with-property/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-build-number.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-multiple-props.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-simple.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-855/pom-undefined.xml
Fixing a regression after #799 
The premise of that PR was that the mojo was updating every file if it **did not** find any match anywhere. This made the mojo update files where e.g. the version was specified as a parameter. 
The fix does it differently -- by resolving parameters and checking if they match the artifact coordinates.
> Resolves #855: Set should evaluate expressions

- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersion.java
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/MercuryVersionComparator.java
This is a simple fix for #869.
This can improve performance in pathetic corner cases by up to 50%. From some example executions (something similar as the pathetic case in #869):
Before:
```
[INFO] Total time:  01:51 min
```
After:
```
[INFO] Total time:  43.714 s
```
In this first implementation, the cache is unbounded. In all my tests it never grew over ~1500 entries, but it might keep some memory active in pathetic cases...
PS: I used a ConcurrentHashMap, because I don't know how parallel (if at all?) Maven can run this code...
> Add a simple cache for ComparableVersions

- pom.xml
- versions-maven-plugin/pom.xml
- versions-test/pom.xml
Some of transitive dependencies can be managed to newer versions.
Added:
- commons-beanutils
- commons-codec
- commons-io
- dom4j
- plexus-archiver
> Manage transitive dependencies version for security updates

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseNextReleasesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseNextVersionsMojoTest.java
Fixes an ArrayOutOfBound introduced by me in #813
> Resolves #889: Fixing ArrayIndexOutOfBound from UseNextVersionsMojo and UseNextReleasesMojo in case of no newer versions/releases

- pom.xml
- versions-common/pom.xml
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/ComparableVersion.java
> Resolves #892: Restrict the ComparableVersion cache size

- versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
> Remove unnecessary synchronization in AbstractVersionDetails

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextReleasesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseNextVersionsMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseNextReleasesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseNextVersionsMojoTest.java
The three mojos in the summary did not have the "allowDowngrade" capability. Adding it for consistence.
> Enhancement: add allowDowngrade capability to UseLatestReleasesMojo, UseNextReleasesMojo, UseNextVersionsMojo

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
This is a (quite) sizeable refactoring job of DisplayPluginUpdates. It already includes #886 as I was doing this while getting to the root cause of #550. In any case, I appreciate that this is a large PR and takes time to analyse.
The goal was to make the class easier to read and understand: after all, the logic is not that complex, it's just the sheer size of it which makes it cumbersome to analyse.
> Refactoring of DisplayPluginUpdates

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
- allows to disable property interpolation, so that it's possible to match against raw property values as well as replace properties with interpolated values if the value is the same as the property value
This is my take on resolving the problem which occurs when the user wants to match against a version which is the same as the interpolated property value. If this is the case, by default, the file is left unchanged, so that it continues to contain the properties.
If the new parameter is employed, it is possible to disable interpolation for such cases, but one needs to match against the raw value (e.g. use the property name, or `*`), and the value will be replaced.
> Resolves #888: New optional parameter to SetMojo: interpolateProperties

- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- versions-maven-plugin/src/it/it-display-parent-updates-no-updates/invoker.properties
- versions-maven-plugin/src/it/it-display-parent-updates-no-updates/pom.xml
- versions-maven-plugin/src/it/it-display-parent-updates-no-updates/verify.groovy
- versions-maven-plugin/src/it/it-display-parent-updates-simple-update/invoker.properties
- versions-maven-plugin/src/it/it-display-parent-updates-simple-update/pom.xml
- versions-maven-plugin/src/it/it-display-parent-updates-simple-update/verify.groovy
- versions-maven-plugin/src/it/it-display-parent-updates-snapshots/invoker.properties
- versions-maven-plugin/src/it/it-display-parent-updates-snapshots/pom.xml
- versions-maven-plugin/src/it/it-display-parent-updates-snapshots/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
- Version range should not be specified in the retrieval at all; removed.
- If provided, the actual version range restriction should be used, and not the result of the toString() method
- Also, allowSnapshots was ignored for the mojo; corrected
> Fixes #896: Fixing available version retrieval; enabling allowSnapshots

- versions-maven-plugin/pom.xml
- versions-maven-plugin/src/it/it-lock-snapshots-junit5/invoker.properties
- versions-maven-plugin/src/it/it-lock-snapshots-junit5/pom.xml
- versions-maven-plugin/src/it/it-lock-snapshots-junit5/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/LockSnapshotsMojoTest.java
It would be ideal if the Resolver method https://maven.apache.org/resolver/maven-resolver-api/apidocs/org/eclipse/aether/RepositorySystem.html#resolveVersion(org.eclipse.aether.RepositorySystemSession,org.eclipse.aether.resolution.VersionRequest) be tested too, but it's rather a test of the Resolver itself.
Edit: Ah, perhaps the its's simply not supported by mrm: https://github.com/mojohaus/mrm/pull/22
> Resolves #899: Corrected the invocation of Resolver to retrieve the timestamped snapshot version

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetPropertyMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set-property/profiled-new-version/pom.xml
Add profileId property to manage the property value to set
> Fixed #911- add profile parameter in set-property

- versions-maven-plugin/src/it/it-compare-dependencies-006/invoker.properties
- versions-maven-plugin/src/it/it-compare-dependencies-006/pom.xml
- versions-maven-plugin/src/it/it-compare-dependencies-006/test.properties
- versions-maven-plugin/src/it/it-compare-dependencies-006/verify.bsh
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
This implements one of the features requested in mojohaus#123 : filtering of artifacts based on their scope.
It adds a scope property to the plugin configuration.
When this is set, only artifacts matching this scope (or ones implied in the maven scope hierarchy) are included.
I made a test for the compare-dependencies goal as it is here that I intend to use it, but it applies to all the goals.
My need it to run comparison only on `compile` dependencies (excluding the tests one that are included in the comparison by default)
(I tried this PR a long time ago as #334 but it went stale and I did not follow up on it at the time)
> Fixes mojohaus#123: add scope filtering

- pom.xml
- versions-maven-plugin/pom.xml
- versions-maven-plugin/src/it/it-changerecord-update-parent-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-update-properties-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-use-latest-releases-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-use-latest-snapshots-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-use-latest-versions-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-use-next-versions-001/verify.groovy
- versions-maven-plugin/src/it/it-compare-dependencies-issue-289/verify.groovy
- versions-maven-plugin/src/it/it-force-releases-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-lock-snapshots-junit/verify.groovy
- versions-maven-plugin/src/it/it-unlock-snapshots-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-use-dep-version-001/verify.groovy
- versions-maven-plugin/src/it/it-use-dep-version-002/verify.groovy
- versions-maven-plugin/src/it/it-use-dep-version-003/verify.groovy
- versions-maven-plugin/src/it/it-use-dep-version-004/verify.groovy
- versions-maven-plugin/src/it/it-use-dep-version-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-use-latest-releases-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-use-latest-snapshots-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-use-latest-versions-009/verify.groovy
- versions-maven-plugin/src/it/it-use-latest-versions-010/verify.groovy
- versions-maven-plugin/src/it/it-use-latest-versions-011/verify.groovy
- versions-maven-plugin/src/it/it-use-latest-versions-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-use-next-releases-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-use-next-snapshots-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-use-releases-issue-134/verify.groovy
- versions-maven-plugin/src/it/it-xml-property-updates-report-001/verify.groovy
- execute spotless by JDK 11
- add missing import for groovy XmlSlurper in ITs
> Bump parent from 72 to 73

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseDepVersionMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/issue-925/pom.xml
If a dependency version was declared in dependency management and dependency processing was enabled, `UseDepVersion` threw an NPE when trying to trim the dependency version, which was null.
Protecting against that case by outputting a warning message if an attempt is made to update such a dependency; by default, if dependency management processing is enabled, the version will be updated during dependency management processing.
@slachiewicz @slawekjaranowski @olamy please review
> Issue #925: Protect against an NPE if a dependency version is defined in dependencyManagement

- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersion.java
- versions-common/src/test/java/org/codehaus/mojo/versions/ordering/VersionComparatorTestBase.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/update-properties/issue-929/pom.xml
NumericVersionComparator's implementation actually requires all versions to produce the String representation of the version in their #toString method. 
Otherwise numeric comparison will not work properly. Amended BoundArtifactVersion.
@slawekjaranowski @slachiewicz please review
> BoundArtifactVersion.toString() to work with NumericVersionComparator

- pom.xml
This fixes the warning issues by Maven 3.9.2.
@slawekjaranowski @slachiewicz please review
> Resolves #954: Excluded plexus-container-default

- versions-enforcer/src/it/it-max-dependency-updates-001/pom.xml
- versions-enforcer/src/it/it-max-dependency-updates-002/pom.xml
- versions-enforcer/src/it/it-max-dependency-updates-003/pom.xml
- versions-enforcer/src/it/it-max-dependency-updates-004/pom.xml
- versions-enforcer/src/it/it-max-dependency-updates-005/pom.xml
- versions-enforcer/src/it/it-max-dependency-updates-006/pom.xml
plugin/goals is deprecated in mvn4 was removed
plugin/executions/execution/goals should be used
> Fix deprecated goals in ITs poms

- versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
- versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts-iso8859-1/invoker.properties
- versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts-iso8859-1/pom.xml
- versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts-iso8859-1/verify.groovy
- versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts/invoker.properties
- versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts/pom.xml
- versions-maven-plugin/src/it/it-use-dep-version-issue-931-umlauts/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
As shown in #931, recent changes introduced in 2.15.0 introduced a regression when the user used irregular characters.
The problem is highly platform dependent and occurs when the `file.encoding` system property does not equal to the one returned by `Charset.defaultCharset()`.
In this particular case, we were using String(byte[]) to construct a String from a byte array which assumed incorrect encoding.
The file was an utf-8 file, but `file.encoding` was equal to `latin1` or `windows1252`. 
> Resolves #931: Fixing problems with encoding in UseDepVersion and PomHelper

- versions-enforcer/src/main/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdates.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- versions-maven-plugin/src/site/markdown/examples/display-dependency-updates.md
- versions-maven-plugin/src/site/markdown/faq.md
Added extended documentation on dependencyIncludes/dependencyExcludes with a faq section and an example.
@slawekjaranowski please consider this for the upcoming release.
> Resolves #921: Clarify dependencyIncludes/dependencyExcludes

- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- versions-common/src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
by default plugin central remote repositories has set update policy as NEVER for update checking it can be not the best way
So every update policy NEVER - will be changed to DAILY
> Use update policy DAILY instead of NEVER for remote repositories

- versions-common/src/main/java/org/codehaus/mojo/versions/api/AbstractVersionDetails.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
- versions-common/src/test/java/org/codehaus/mojo/versions/api/AbstractVersionDetailsTest.java
- versions-enforcer/src/main/java/org/apache/maven/plugins/enforcer/MaxDependencyUpdates.java
- versions-maven-plugin/src/it/it-display-dependency-updates-issue-973-versionless/invoker.properties
- versions-maven-plugin/src/it/it-display-dependency-updates-issue-973-versionless/pom.xml
- versions-maven-plugin/src/it/it-display-dependency-updates-issue-973-versionless/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReportMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPluginUpdatesReportMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
In case a dependency version is specified in dependencyManagement, a dependency can be versionless.
Dependency updates goals would then attempt to find an updated version to a versionless dependency, which would fail with an NPE or, if that is prevented, an attempt would have been made to find an update to version specified as [,0], which would be any version.
Preventing both issues.
@slawekjaranowski please review.
> Resolves #973: NPE if actual version is null for a dependency

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/MinimalMavenBuildVersionFinder.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/MinimalMavenBuildVersionFinderTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-plugin-updates/issue-990/no-enforcer.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-plugin-updates/issue-990/no-prerequisites.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-plugin-updates/issue-990/prerequisites-greater.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-plugin-updates/issue-990/prerequisites-lesser.xml
Check prerequisites if enforcer check for Maven version is not present.
~~Prerequisites are checked after enforcer -- disputable, but at least this keeps the behavior backwards compatible.~~
The plugin will choose the version which is the highest between: default maven version, prerequisites, enforcer.
@slawekjaranowski please check
> Resolves #990: Check prerequisites if required enforcer Maven version is empty

- versions-maven-plugin/src/it/it-update-parent-latest-version/invoker.properties
- versions-maven-plugin/src/it/it-update-parent-latest-version/pom.xml
- versions-maven-plugin/src/it/it-update-parent-latest-version/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
Displaying `No versions found` can be confusing
> Correct message if the latest version of parent is used for update-parent

- versions-maven-plugin/src/it/it-use-releases-issue-978-parent-snapshot/invoker.properties
- versions-maven-plugin/src/it/it-use-releases-issue-978-parent-snapshot/pom.xml
- versions-maven-plugin/src/it/it-use-releases-issue-978-parent-snapshot/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseReleasesMojoTest.java
- added an it testing against a plain (not timestamped) -SNAPSHOT
- added a unit test testing against a timestamped snapshot
- added another comparison for the base version if it exists
> Resolves #978 - use-releases does not update parent

- versions-common/src/main/java/org/codehaus/mojo/versions/api/PluginUpdatesDetails.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MiscUtils.java
- versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/invoker.properties
- versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/module-a1/pom.xml
- versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/module-a2/pom.xml
- versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/module-a3/pom.xml
- versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/module-a4/pom.xml
- versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/pom.xml
- versions-maven-plugin/src/it/it-aggregate-plugn-multiple-versions-same-plugin/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractPluginUpdatesReportMojo.java
Signed-off-by: Olivier Lamy <olamy@apache.org>
> Fix ISE with plugins aggregate report when reactor projects contains the same plugin declaration multiple time with different versions

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
> update javadoc at-since annotation to 2.16.2

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-1042/child-webapp/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-1042/main-reactor/package-parent/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-1042/main-reactor/pom-parent/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-1042/main-reactor/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-1042/pom.xml
#1042 is a pretty particular case which exposes a bug in the set logic.
The new version is initially set "to be tried out". Then, it is being set for the second time when processing changes. However, there's also some logic which is supposed to see if there are modules using the module that is being changed. This logic was responsible for the reversed change in the case of this particular issue. 
When investigating, I've noticed that `processAllModules` has two meanings: one is to process two modules regardless whether they match the current module; the second makes the matching logic traverse the whole reactor instead of the current module's subtree in search of modules which use the current module as parent. Because of that, I have introduced a new option, `fullTreeMatch`, which should …
> Resolves #1042: Fixed set logic wrt processAllModules

- .github/workflows/maven.yml
ITs will be executed in matrix in parallel, so we should have a shorter time for whole build.
> Execute fail-fast job without ITs

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojo.java
The field value is overwritten by `Parameter#defaultValue` anyway, but the mismatching initial field value might lead to confusion nonetheless.
Looks like this was an oversight when #817 changed the `defaultValue`.
> Fix `includeParent` field value not matching `Parameter#defaultValue`

- versions-maven-plugin/src/it/it-set-issue-1103/invoker.properties
- versions-maven-plugin/src/it/it-set-issue-1103/parent/child/grandchild/pom.xml
- versions-maven-plugin/src/it/it-set-issue-1103/parent/child/pom.xml
- versions-maven-plugin/src/it/it-set-issue-1103/parent/pom.xml
- versions-maven-plugin/src/it/it-set-issue-1103/pom.xml
- versions-maven-plugin/src/it/it-set-issue-1103/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
I reverted changes from #1051 
Issue #1042 was fixed in a simple way
> Revert #1051 - fix #1110, #1103

- versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
The same pattern can be compiled once.
> Extract Pattern.compile to static variable

- versions-maven-plugin/src/it-repo/it-resolve-ranges-issue-1121-parent.pom
- versions-maven-plugin/src/it/it-resolve-ranges-issue-1121/invoker.properties
- versions-maven-plugin/src/it/it-resolve-ranges-issue-1121/pom.xml
- versions-maven-plugin/src/it/it-resolve-ranges-issue-1121/verify.bsh
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
PR for #1121 
If 'includeProperties' is null, use it to restrict the properties that are considered in the resolve-ranges mojo to those from the current project. Otherwise, user will normally have included only a subset of those.
Also added an it to cover the situation in #367 as this wasn't covered yet and led me to believe at first that setting 'includeParent' to false in the VersionPropertiesMapRequest was enough.
> Improve speed of versions:resolve-ranges in case parents contain many version properties

- versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/change/AbstractVersionChanger.java
- versions-common/src/main/java/org/codehaus/mojo/versions/change/DependencyVersionChanger.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsDependencyUpdaterMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/LockSnapshotsMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/ResolveRangesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UnlockSnapshotsMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReactorMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ForceReleasesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/LockSnapshotsMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestReleasesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseNextReleasesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseNextVersionsMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseReleasesMojoTest.java
When running the `versions:set` goal, the console is full of `expression: {blah} no value` messages.
Further investigation identified this occurs when a `pom` contains a property declared in a parent `pom`.
In `PomHelper#getRawModel`:
https://github.com/mojohaus/versions/blob/be0e260a1b45b713ccc1bd09bd93908468c98df4/versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java#L127
As such the parent properties are no longer accessible downstream.
Based on this, being unable to evaluate an expression is not unexpected and does not need to appear in any non-`debug` log.
This can be reproduced with a parent:
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 …
```
> Move `expression: {blah} no value` `System.out` to logs

- versions-common/src/main/java/org/codehaus/mojo/versions/api/ArtifactVersionsCache.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
Map is not thread safe but some mojo are marked thread safe.
This PR use a safe structure.
_PS: null check added because ConcurrentHashMap does not accept null value (diff with HashMap)_
> bugix/ protect internal data in multi thread env.

- versions-maven-plugin/src/site/markdown/version-rules.md.vm
Fix #1144 by appending `.+` to the `.+-(alpha|beta)` part, regarding versions such as `1.0-beta-1`.
> Fix #1144 / appends `.+` to `.+-(alpha|beta)`

- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
- versions-common/src/test/java/org/codehaus/mojo/versions/utils/MavenProjectUtilsTest.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReportMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
There is a possible NPE if a depden… dencyManagement entry has no version.
Added a couple unit tests to interpolateVersion.
interpolateVersion does not mutate the dependency anymore but returns a modified copy if it needs to modify it.
> Resolves#1066: Fixed a possible NPE in interpolateVersion

- src/site/site.xml
- versions-api/src/site/site.xml
- versions-enforcer/src/site/site.xml
- versions-maven-plugin/src/site/site.xml
- versions-model-report/src/site/site.xml
- versions-model/src/site/site.xml
With m-site-p 3.20.+ we have new site descriptor.
> Update site descriptor to 2.x

- versions-common/src/main/java/org/codehaus/mojo/versions/api/ArtifactVersions.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/PluginUpdatesDetails.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/AbstractVersionComparator.java
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersion.java
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/MavenVersionComparator.java
- versions-common/src/main/java/org/codehaus/mojo/versions/ordering/VersionComparators.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/DelegatingContextualLog.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/DependencyBuilder.java
- versions-common/src/test/java/org/codehaus/mojo/versions/filtering/DependencyFilterTest.java
- versions-common/src/test/java/org/codehaus/mojo/versions/filtering/TokenizedMatcherTest.java
- versions-common/src/test/java/org/codehaus/mojo/versions/utils/SegmentUtilsTest.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/CommitMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DynamicVersioningSCMPlugin.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetScmTagMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/LockSnapshotsMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PluginUpdatesXmlRendererTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseNextReleasesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseNextVersionsMojoTest.java
Move from Plexus StringUtils to Apache Commons. Improved ArtifactVersions::compareTo and added a stricter one for PluginUpdatesDetails to comfort static code checkers.
> Resolves#1169: Clean-up, remove deprecated methods, remove Plexus StringUtils in favour of Apache Commons

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
> Resolves #1060: Bugfix in UpdateParentMojo + add tests

- versions-common/src/main/java/org/codehaus/mojo/versions/utils/DependencyComparator.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
- versions-maven-plugin/src/it/it-dependency-updates-report-issue-1140/child/pom.xml
- versions-maven-plugin/src/it/it-dependency-updates-report-issue-1140/invoker.properties
- versions-maven-plugin/src/it/it-dependency-updates-report-issue-1140/pom.xml
- versions-maven-plugin/src/it/it-dependency-updates-report-issue-1140/verify.groovy
- versions-maven-plugin/src/it/it-display-dependency-updates-009-processDependencyManagementTransitive-true/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReport.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesAggregateReport.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
I managed to reproduce #1140 for reports, so here is a fix.
Added an integration test + showVersionless for dependency-updates-report.
Added some small refactoring.
> Fixes #1140 for reports

- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
- versions-maven-plugin/src/it/it-changerecord-update-parent-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-update-properties-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-use-latest-releases-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-use-latest-snapshots-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-use-latest-versions-001/verify.groovy
- versions-maven-plugin/src/it/it-changerecord-use-next-versions-001/verify.groovy
- versions-maven-plugin/src/it/it-dependency-updates-report-issue-1191/invoker.properties
- versions-maven-plugin/src/it/it-dependency-updates-report-issue-1191/pom.xml
- versions-maven-plugin/src/it/it-dependency-updates-report-issue-1191/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReport.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-dependency-updates/profiles/pom.xml
If processDependencyManagementTransitive is false, will also process dependency management entries from profiles (all profiles). 
This was previously reported as a bug.
> Fixed #1191: Processes (all) profiles from original model if transitive is false

- versions-maven-plugin/src/it-repo/dummy-aggregate-child-1.0.1.pom
- versions-maven-plugin/src/it-repo/dummy-aggregate-parent-1.0.1.pom
- versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/child-one/pom.xml
- versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/child-two/pom.xml
- versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/invoker.properties
- versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/pom.xml
- versions-maven-plugin/src/it/it-dependency-updates-aggregate-report-issue-333/verify.groovy
- versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/child-one/pom.xml
- versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/child-two/pom.xml
- versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/invoker.properties
- versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/pom.xml
- versions-maven-plugin/src/it/it-plugin-updates-aggregate-report-issue-333/verify.groovy
- versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/child-one/pom.xml
- versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/child-two/pom.xml
- versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/invoker.properties
- versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/pom.xml
- versions-maven-plugin/src/it/it-property-updates-aggregate-report-issue-333/verify.groovy
Several issues with integration tests for #333 caused it to break the release build with Maven 4.
> Fixed the failed release build

- .github/workflows/pr-automation.yml
Only `pull_request_target` - use GITHUB_TOKEN with write access for PR from forked repository
We need a write access to change a label or milestone.
> PR Automation - must use pull_request_target

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
This was actually suggested earlier for property updates.
Update retrieval (which is immutable) is split from update execution which made parallel updates feasible.
`ConcurrentLinkedQueue` is chosen as the structure for appending updates (it's being written to by multiple threads).
Introduced a new parameter, `numThreads`.
Also, bumped version to `2.19.0-SNAPSHOT`
> Parallel version updates

- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionRetrievalException.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
- versions-common/src/test/java/org/codehaus/mojo/versions/ordering/BoundArtifactVersionTest.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/AbstractDependencyUpdatesReport.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesAggregateReport.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojoBase.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseReleasesMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DependencyUpdatesReportTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/DisplayPropertyUpdatesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/ParentUpdatesReportTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PluginUpdatesReportTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/PropertyUpdatesReportTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTestBase.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UpdatePropertyMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseDepVersionMojoTest.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseLatestVersionsMojoTestBase.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/UseReleasesMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-dependency-updates/problem-causing/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/display-plugin-updates/problem-causing.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/update-properties/problem-causing/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/use-dep-version/problem-causing/pom.xml
Any problems causing the Resolver to fail resolving a version should be reported to the end user,  including the artifact causing the problem which can facilitate problem resolution on the resolver end. 
Here we're propagating the information about the problematic artifact to the mojo which can then output it in the log.
Related: #1147
> Exposing the problem causing artifact if Resolver throws an exception

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetPropertyMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set-property/profiled-new-version-without-props/pom.xml
Handles the case when the property is not in the project properties but it is present in the profile properties
> Fixed #1233- set-property in profile without module  property

- versions-common/src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/PropertyVersionsBuilder.java
- versions-common/src/main/java/org/codehaus/mojo/versions/api/VersionsHelper.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojoBase.java
Include/exclude filters were being applied after all versions updates have been retrieved. If the user used those filters, a lot of property versions have been retrieved unnecessarily.
@slawekjaranowski please review.
> Resolves #1266: Applying the include filter during association resolution

- versions-common/src/main/java/org/codehaus/mojo/versions/utils/DependencyComparator.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/PluginComparator.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/PropertyComparator.java
- versions-common/src/main/java/org/codehaus/mojo/versions/utils/VersionStringComparator.java
- versions-common/src/test/java/org/codehaus/mojo/versions/utils/DependencyComparatorTest.java
- versions-common/src/test/java/org/codehaus/mojo/versions/utils/PluginComparatorTest.java
Now this is a "business" kind of bug and I am surprised that this hasn't come up before. Dependencies, Plugins, etc, all use regular lexicographic comparison to order versions (where this is done by the plugin and not Resolver) whereas it should use semantic versioning (for example `GenericVersion` from Resolver).
I guess this hasn't been noticed because most people don't have any strange versioning schemes, but I have added some unit tests which break with regular string comparison (e.g. `1.0` should be equivalent to `1.0.0`, etc.).
> Artifact comparison should use semantic version comparison.
