- src/main/java/org/codehaus/mojo/versions/SetMojo.java
This solves problems when using the plugin in multi module projects with a flat module structure.
> Fixed incorrect project parameter.

- src/it/it-set-009/alternative-pom.xml
- src/it/it-set-009/child/pom.xml
- src/it/it-set-009/invoker.properties
- src/it/it-set-009/verify.groovy
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
This commit contains contains the code for fix #43 and a integration test to ensure the functionality.
> Fixes #43 Added suport to run versions:set with the "--file" maven parameter

- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
> Fixed bug which platform encoding is used by `java.io.FileReader`

- src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
this is a fix for https://github.com/mojohaus/versions-maven-plugin/issues/25
> fix #25 use raw model for dependencyManagement

- src/it/it-set-001/invoker.properties
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
Fixes #83 and #38 issues and add a integration test that simulate the issues.
> Fixes #83 and #38

- src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
This PR supersedes https://github.com/mojohaus/versions-maven-plugin/pull/52. I took the liberty of squashing @designhaiku's commits into one, as per @tchemit's request.
> versions:set - add "removeSnapshot" property (squashed)

- src/main/java/org/codehaus/mojo/versions/DependencyUpdatesReport.java
- src/main/java/org/codehaus/mojo/versions/PluginUpdatesReport.java
Parameter added to dependency update report formats.
> Fixed #185: add parameter for dependency update report formats

- src/it-repo/module-a1-1.0.pom
- src/it-repo/the-grandparent-1.0.pom
- src/it-repo/the-parent-1.0.pom
- src/it/it-use-reactor-001/invoker.properties
- src/it/it-use-reactor-001/module-a1/pom.xml
- src/it/it-use-reactor-001/module-a2/pom.xml
- src/it/it-use-reactor-001/pom.xml
- src/it/it-use-reactor-001/the-grandparent/pom.xml
- src/it/it-use-reactor-001/the-parent/pom.xml
- src/it/it-use-reactor-001/verify.bsh
- src/it/it-use-reactor-002/invoker.properties
- src/it/it-use-reactor-002/module-a1/pom.xml
- src/it/it-use-reactor-002/module-a2/pom.xml
- src/it/it-use-reactor-002/pom.xml
- src/it/it-use-reactor-002/the-grandparent/pom.xml
- src/it/it-use-reactor-002/the-parent/pom.xml
- src/it/it-use-reactor-002/verify.bsh
- src/main/java/org/codehaus/mojo/versions/UseReactorMojo.java
See #202 for additional information.
> Fix #202 - use-reactor update parents

- src/it/it-use-latest-releases-006/invoker.properties
- src/it/it-use-latest-releases-006/pom.xml
- src/it/it-use-latest-releases-006/verify.bsh
- src/it/it-use-latest-releases-007/invoker.properties
- src/it/it-use-latest-releases-007/pom.xml
- src/it/it-use-latest-releases-007/verify.bsh
- src/it/it-use-latest-snapshots-003/invoker.properties
- src/it/it-use-latest-snapshots-003/pom.xml
- src/it/it-use-latest-snapshots-003/verify.bsh
- src/it/it-use-latest-snapshots-004/invoker.properties
- src/it/it-use-latest-snapshots-004/pom.xml
- src/it/it-use-latest-snapshots-004/verify.bsh
- src/it/it-use-latest-versions-009/invoker.properties
- src/it/it-use-latest-versions-009/pom.xml
- src/it/it-use-latest-versions-009/verify.bsh
- src/it/it-use-latest-versions-010/invoker.properties
- src/it/it-use-latest-versions-010/pom.xml
- src/it/it-use-latest-versions-010/verify.bsh
- src/main/java/org/codehaus/mojo/versions/UseLatestReleasesMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestSnapshotsMojo.java
- src/main/java/org/codehaus/mojo/versions/UseLatestVersionsMojo.java
Adding parent processing to UseLatestVersion/UseLatestSnapshot/UseLatestRelease
> Fixed #237

- src/site/apt/index.apt
> Minor spelling corrections

- src/it/it-set-017-issue-321/invoker.properties
- src/it/it-set-017-issue-321/module-a1/pom.xml
- src/it/it-set-017-issue-321/module-a2/pom.xml
- src/it/it-set-017-issue-321/pom.xml
- src/it/it-set-017-issue-321/verify.bsh
- src/main/java/org/codehaus/mojo/versions/AbstractVersionsUpdaterMojo.java
- src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
- src/main/java/org/codehaus/mojo/versions/rewriting/ModifiedPomXMLEventReader.java
- src/test/java/org/codehaus/mojo/versions/RewriteWithStAXTest.java
- src/test/java/org/codehaus/mojo/versions/api/PomHelperTest.java
> Fixes #321 fail the build when parsing XML of child modules fails due to invalid XML

- src/it/it-set-018-issue-82/invoker.properties
- src/it/it-set-018-issue-82/module-a1/module-b1/pom.xml
- src/it/it-set-018-issue-82/module-a1/module-b2/pom.xml
- src/it/it-set-018-issue-82/module-a1/module-b3/pom.xml
- src/it/it-set-018-issue-82/module-a1/pom.xml
- src/it/it-set-018-issue-82/module-a2/pom.xml
- src/it/it-set-018-issue-82/pom.xml
- src/it/it-set-018-issue-82/verify.groovy
- src/main/java/org/codehaus/mojo/versions/SetMojo.java
- src/main/java/org/codehaus/mojo/versions/api/PomHelper.java
> Fixes #82 ensure version change affects only the current directory (and child directories), not the parent or sibling directories

- src/site/apt/version-rules.apt.vm
- src/test/resources/org/codehaus/mojo/versions/api/rules.xml
> Fix #306: Adjust rules schemaLocation

- src/it/it-display-plugin-updates-009-issue-422/invoker.properties
- src/it/it-display-plugin-updates-009-issue-422/pom.xml
- src/it/it-display-plugin-updates-009-issue-422/verify.bsh
- src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
> Fixes #422 Avoid NPE when non-local parent POM is present

- src/main/java/org/codehaus/mojo/versions/api/DefaultVersionsHelper.java
See : https://github.com/mojohaus/versions-maven-plugin/issues/439
> Fixes #439 : String index out of range: 9

- pom.xml
- src/test/java/org/codehaus/mojo/versions/api/DefaultVersionsHelperTest.java
Updating dependencies, instead of big bang PR, doing each as separate PR
> hamcrest v2.2

- src/it/it-set-property-002/verify.bsh
- src/it/it-set-property-003-multiple-properties/invoker.properties
- src/it/it-set-property-003-multiple-properties/pom.xml
- src/it/it-set-property-003-multiple-properties/verify.bsh
- src/main/java/org/codehaus/mojo/versions/SetPropertyMojo.java
> #543 set-property: add back support for multiple property names separates by ","

- src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
> #538 switch to non-deprecated ModelInterpolator

- src/it/it-display-plugin-updates-011-ignore-plugin-defined-in-parent/invoker.properties
- src/it/it-display-plugin-updates-011-ignore-plugin-defined-in-parent/parent/pom.xml
- src/it/it-display-plugin-updates-011-ignore-plugin-defined-in-parent/pom.xml
- src/it/it-display-plugin-updates-011-ignore-plugin-defined-in-parent/verify.bsh
- src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
> #550 ignore plugins which have no version in current POM but in parent POM

- pom.xml
- src/site/site.xml
- use configuration and plugins version from parent
- execute mrm in run-its profile
- remove plexus-container-default from dependencies
- add breadcrumbs for site
> Cleanup project pom file

- src/main/java/org/codehaus/mojo/versions/SetMojo.java
- src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
Implementing the requested feature.
> support to increase x or y in version of x.y.z, not only z #539

- src/test/java/org/codehaus/mojo/versions/UpdateParentMojoTest.java
As requested, adding a simple unit test verifying that #690 is fixed
> #690: Adding a unit test testing the issue

- src/site/markdown/examples/advancing-dependency-versions.md.vm
- src/site/markdown/examples/display-plugin-updates.md
- src/site/markdown/faq.md
- src/site/markdown/index.md
- src/site/markdown/usage.md.vm
- src/site/markdown/version-rules.md.vm
I've also noticed that I made a typo in the "author" metadata -- correcting it.
> #725: Migrating the plugin dependency updates example

- src/it-repo/dummy-parent5-1.0.0.pom
- src/it-repo/dummy-parent5-2.0.0-rc1.pom
- src/it/it-resolve-ranges-issue-454/invoker.properties
- src/it/it-resolve-ranges-issue-454/pom.xml
- src/it/it-resolve-ranges-issue-454/verify.groovy
- src/it/it-update-parent-issue-454/invoker.properties
- src/it/it-update-parent-issue-454/pom.xml
- src/it/it-update-parent-issue-454/verify.groovy
- src/main/java/org/codehaus/mojo/versions/UpdatePropertiesMojo.java
- src/main/java/org/codehaus/mojo/versions/UpdatePropertyMojo.java
- src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java
- src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTest.java
- src/test/java/org/codehaus/mojo/versions/UpdatePropertiesMojoTestBase.java
- src/test/java/org/codehaus/mojo/versions/UpdatePropertyMojoTest.java
- src/test/java/org/codehaus/mojo/versions/utils/TestUtils.java
- src/test/resources/org/codehaus/mojo/update-properties/issue-454-pom.xml
High prio PR, fixes #454 for `UpdatePropertiesMojo`
Regarding #454, perhaps it should be reopened 😄
> #454 Use BoundArtifactVersion with UpdatePropertiesMojo

- src/main/java/org/codehaus/mojo/versions/reporting/AbstractVersionsReportRenderer.java
- src/main/java/org/codehaus/mojo/versions/reporting/PluginUpdatesReportRenderer.java
> #762 Fix Plugin Report and Success/Warning icons, counts

- pom.xml
https://github.com/mojohaus/mojo-parent/releases/tag/71
> Bump parent version from 70 to 71

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
> Resolves #850: Protecting the display-plugin-updates mojo against a NPE in case the effective version of a plugin is not resolved

- versions-maven-plugin/pom.xml
> Fixes #866: Require maven 3.2.5

- versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/invoker.properties
- versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/parent.xml
- versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/pom.xml
- versions-maven-plugin/src/it/it-display-plugin-updates-issue-533/verify.groovy
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
- if true, will show updates to plugins defined in parent poms, which have no version in the current pom
- false by default to retain backwards compatibility
> Resolves #533: New parameter to DisplayPluginUpdatesMojo: processUnboundPlugins

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
@slawekjaranowski please merge
> Resolves #906: Typo

- versions-maven-plugin/src/it/it-plugin-updates-report-issue-755/pom.xml
- versions-maven-plugin/src/it/it-plugin-updates-report-issue-755/verify.groovy
We can not use version of production artifact
it can change between build
> Use versions of dummy artifacts in IT assertions

- versions-maven-plugin/src/it/it-display-dependency-updates-issue-1001-groupid/invoker.properties
- versions-maven-plugin/src/it/it-display-dependency-updates-issue-1001-groupid/pom.xml
- versions-maven-plugin/src/it/it-display-dependency-updates-issue-1001-groupid/verify.groovy
Added a test case cheching the case indicated in the issue
> #1001: added a test case for the issue

- pom.xml
> Manage byte-buddy version in order to support build with JDK 21

- README.md
- pom.xml
- versions-api/pom.xml
- versions-common/pom.xml
- versions-enforcer/pom.xml
- versions-maven-plugin/pom.xml
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayParentUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java
- versions-model-report/pom.xml
- versions-model/pom.xml
- versions-test/pom.xml
- follow hints from dependency:analyze
> Require Maven 3.6.3, dependencies cleanups

- versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-0-commits-0-tags/invoker.properties
- versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-1-commit-0-tags/invoker.properties
- versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-4-commits-1-vtag/invoker.properties
- versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-latest-commit/invoker.properties
- versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-append-snapshot/invoker.properties
- versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-param-use-versions/invoker.properties
- versions-maven-plugin/src/it/it-dynamic-versioning-scm-tag-property-name/invoker.properties
- versions-maven-plugin/src/it/it-set-004/invoker.properties
https://issues.apache.org/jira/browse/MNG-8211
> Disable ITs with not set CI Friendly with newer Maven version

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
- versions-maven-plugin/src/test/java/org/codehaus/mojo/versions/SetMojoTest.java
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-1137/child/pom.xml
- versions-maven-plugin/src/test/resources/org/codehaus/mojo/set/issue-1137/pom.xml
- versions-test/src/main/java/org/codehaus/mojo/versions/utils/TestLog.java
> Resolves #1137: using PomHelper.getGroupId if groupId of the current project root is empty

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/CompareDependenciesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayPluginUpdatesMojo.java
bug fix in CompareDependenciesMojo::getRemoteMavenProject, likewise in DisplayPluginUpdatesMojo::getPluginProject
> Resolves #1067: Bug fix: incorrect arguments of PomHelper::createProjectBuilderRequest

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/SetMojo.java
Replace (here shown parts from details section)
with
-----
- #570
- #630
> Fix closing code tags

- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayDependencyUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/DisplayExtensionUpdatesMojo.java
- versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/UseDepVersionMojo.java
It is generated by plugin-tools
> Remove manual default from docs for parameters

- versions-maven-plugin/src/site/markdown/index.md
Fixed broken site links; mentioned Github.
> Resolves #1271: Fixed broken Site links

- versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java
- versions-common/src/test/java/org/codehaus/mojo/versions/utils/MavenProjectUtilsTest.java
Simple fix, just for dependencyManagement at the time being, perhaps we will make it global later on.
> Resolves #1150: Resolve multiple level properties (properties resolving to properties)
